_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": linux-x86_64
architecture:
    value: LSTM
batch_size:
    value: 32
dataset:
    value: Self-collected, dataset6
epochs:
    value: 200
hidden_size:
    value: 64
learning_rate:
    value: 0.005
normalization:
    value: Standardized
